LEXICAL_ERROR = 11
SYNTAX_ERROR = 12
SEMANTIC_TYPE_CHECK_ERROR = 13
SEMANTIC_DECLARATION_ERROR = 14
CODE_GENERATION_ERROR = 15 # eg. not enough memory
INTERNAL_ERROR = 19

ERROR_MSG_MISSING_ARG = "Missing argument: input file"
ERROR_MSG_FILE_NOT_FOUND = "File not found"
