import re

from src.code_gen.cls import ClassCodeGenerator
from src.code_gen.function import Function
from src.code_gen.if_else import IfElseGenerator
from src.code_gen.literal import Literal
from src.code_gen.register import Register
from src.code_gen.stack import Stack
from src.compiler import CompilerError
from src.sym_table import *


# WARN: for some reason, stack grows up

class CodeGenerator:
    """
    use modified cdecl calling convention
        args are pushed on stack from LTR, callee cleans up, return value on stack
     """

    def __init__(self):
        self.header = '''#! /bin/vypint
# VYPcode: 1.0
# Generated by xdokou14'''
        self.body = ''
        self.variables = []
        self.classes = []
        # TODO: perhaps refactor to function class
        self.params = []
        self.if_else_stack = []
        self.cur_func = None

    def get_var_offset(self, symbol: str) -> str:
        if symbol in self.variables:
            return '+' + str(self.variables.index(symbol) + 1)  # 0 is BP
        elif symbol in self.params:
            # in negative 0-BP, 1-PC, 3-arg1, 4-arg2, 5-arg3, (RTL) ...
            return str(-(self.params.index(symbol) + 2))
        else:
            raise CompilerError(f"Variable {symbol} not found", 14)

    def generate_code(self):
        self.prettifyOutput()
        print(self.header)
        print(Register.aliases())
        print("SET $BP $SP")
        print("CALL [$SP+1] main")
        print("JUMP _end\n")
        print(self.body)
        print("LABEL _end")

    def prettifyOutput(self):
        """add tabs"""

        def add_tabs(match):
            lines = match.group(0).split('\n')
            return '\n' + lines[0] + '\n' + '\n'.join('\t' + line if line else line for line in lines[1:])

        self.body = re.sub(r'LABEL.*?(?=LABEL(!=(end|else|startwhile|endwhile))|$)', add_tabs, self.body,
                           flags=re.DOTALL)

    def declaration(self, symbol: Symbol):
        _name = symbol.name
        self.variables.append(_name)
        _type = symbol.data_type
        self.body += f'# declare {_name}\n'
        self.body += f'SET [{Register.BP}{self.get_var_offset(_name)}] 0\n'
        self.body += f'{Stack.push()}\n\n'

    def fun_call(self, fun: FunctionSymbol, args: [Symbol]):
        f = Function(fun)
        self.body += f.call(args)
        self.cur_func = f

    def literal(self, symbol: Symbol):
        if symbol.data_type == 'int':
            self.body += Literal.int_literal(symbol.name)
        else:
            self.body += Literal.string_literal(symbol.name)

    def restore_stack(self):
        _vars = len(self.variables)
        self.body += f'# restore stack\n'
        self.body += f'ADDI {Register.SP} {Register.BP} {_vars}\n\n'

    def function_def(self, fun_sym: FunctionSymbol):
        function = Function(fun_sym)
        self.body += function.define()

        # add params to stack
        for param in fun_sym.get_params():
            self.params.insert(0, param.name)
        self.cur_func = function  # beware im using this for both definition and call TO be refactored

    def exit_function(self):
        self.cur_func = None
        self.body += Function.exit()
        self.params = []
        self.variables = []

    def VMT(self, current_class: ClassSymbol):
        cls_gen = ClassCodeGenerator(current_class)
        self.classes.append(current_class)
        self.body += cls_gen.VMT()

    def create_instance(self, class_sym: ClassSymbol):
        cls_gen = ClassCodeGenerator(class_sym)
        self.body += cls_gen.create_instance(class_sym, self.classes)

    def assign_field(self, cls_sym, field):
        cls_gen = ClassCodeGenerator(cls_sym)
        self.body += cls_gen.assign_field(field)

    def push_object(self, first: str):
        ref = f'[{Register.BP}{self.get_var_offset(first)}]'

        self.body += f'# push object ref {first}\n'
        self.body += f'{Stack.push(ref)}\n\n'
        # self.body += f'PUSH [{Register.BP}{self.get_var_offset(first)}]\n\n'

    def assign_var(self, _id):
        self.body += f'# assign var {_id}\n'
        self.body += f'SET [{Register.BP}{self.get_var_offset(_id)}] [{Register.SP}]\n\n'

    def field_expr(self, cls_sym, field):
        cls_gen = ClassCodeGenerator(cls_sym)
        self.body += cls_gen.field_expr(field)

    def binary_op(self, op: str):
        map = {
            '+': 'ADDI',
            '-': 'SUBI',
            '*': 'MULI',
            '/': 'DIVI',
            '<': 'LTI',
            '>': 'GTI',
            '=': 'EQI',
            '<': 'LTS',
            '>': 'GTS',
            '==': 'EQS',
            '&&': 'AND',
            '||': 'OR',
        }
        _op = map[op]
        # TODO: exceptions for >=, <=, !=

        self.body += f'# binary operation: {op}\n'
        self.body += f'{Stack.binary_op(_op)}\n\n'

    def ret_val(self, symb: Symbol):
        self.body += self.cur_func.exit_with_val(symb)
        pass

    def gen_enter_if(self, not_label, end_label):
        if_else_generator = IfElseGenerator(not_label, end_label)
        self.if_else_stack.append(if_else_generator)
        self.body += self.if_else_stack[-1].enter_if()

    def gen_enter_else(self):
        self.body += self.if_else_stack[-1].enter_else()

    def gen_exit_if_else(self):
        self.body += self.if_else_stack[-1].exit_if_else()
        self.if_else_stack.pop()
